env:
  TERM: xterm-256color
window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    dynamic_padding: true
    x: 5
    y: 5
  title: Alacritty
  opacity: 0.8

font:
  normal:
    family: "Fira Code"
    style: "Medium"
  bold:
    family: "Fira Code"
    style: "Bold"
  italic:
    family: "Fira Code"
    style: "Italic"
  bold_italic:
    family: "Fira Code"
    style: "Bold Italic"
  size: 9
  builtin_box_drawing: true
  scale_with_dpi: true
  offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: false


cursor:
  style: beam
  vi_mode_style: underline

scrolling:
  history: 10000
  multiplier: 3


key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }

live_config_reload: true
#import:
#  - ~/.config/alacritty/themes/darcula.yaml

    # shell:
    #   program: /bin/bash
    #   args:
    #     - -l
    #     - -c
    #     - "tmux"
