#+AUTHOR: Lucas Elvira
#+DATE 2023-03-19
#+EXPORTS_FILE_NAME: config.html
#+STARTUP: showeverything

* :TOC:
- [[#put-this-in-your-initel][PUT THIS IN YOUR init.el]]
- [[#autorun][AUTORUN]]
  - [[#emacs-as-server][Emacs as server]]
  - [[#which-key][which key]]
- [[#install-packages][Install packages]]
  - [[#setup-melpa-to-enable-install-package][setup melpa to enable install package]]
  - [[#setup-straight][Setup straight]]
  - [[#install-some-package][install some package]]
- [[#ivy-posframe][Ivy-posframe]]
- [[#registers][REGISTERS]]
- [[#file-manager][File manager]]
  - [[#open-dired][Open dired]]
  - [[#keybinding-within-dired][Keybinding within dired]]
  - [[#keybinding-for-peep-dired-mode][Keybinding for peep-dired-mode]]
- [[#keep-folders-clean][keep folders clean]]
- [[#files][Files]]
  - [[#keybindings-for-files][Keybindings for files]]
  - [[#useful-file-functions][Useful file functions]]
- [[#customize-ui][Customize UI]]
  - [[#display-line-numbers][display line numbers]]
  - [[#clean-ui][clean ui]]
  - [[#install-some-themes-and-enable-it][Install some themes and enable it]]
  - [[#buffers-and-bookmarks][Buffers and bookmarks]]
- [[#customization][Customization]]
  - [[#truncate-lines-in-text-mode][Truncate lines in text mode]]
- [[#dashboard][DASHBOARD]]
  - [[#launch-dashboard-by-default-when-launch-emacs][Launch dashboard by default when launch emacs]]
  - [[#shortcuts][Shortcuts]]
  - [[#disable--of-m-x][Disable '^' of M-x]]
  - [[#disable-mouse][Disable mouse]]
- [[#org-mode][ORG MODE]]
  - [[#org-links][Org links]]
  - [[#source-code-blocks][Source code blocks]]
  - [[#configure-some-vars][Configure some vars]]
  - [[#org-capture][Org capture]]
  - [[#org-toc][Org toc]]
  - [[#org-export-manpage][Org export manpage]]
  - [[#org-roam][Org-roam]]
  - [[#org-babel][ORG-BABEL]]
  - [[#source-code-block-tag-expansion][Source Code Block Tag Expansion]]
  - [[#skeletons][Skeletons]]
- [[#custom-hooks][Custom hooks]]

* PUT THIS IN YOUR init.el

#+begin_example
(org-babel-load-file
(expand-file-name
  "config.org"
  user-emacs-directory))
#+end_example
* AUTORUN
** Emacs as server

This command allow to run emacs as server, so all the startup can be done once
time and connect client to it each time you need
#+begin_src emacs-lisp
  (server-start)
#+end_src
*** Connect a client
To connect a client to the server you need to run

#+begin_example shell
emacsclient --create-frame --alternate-editor=""
# or use an alias
export ALTERNATE_EDITOR=""
export EDITOR="emacsclient -t"                  # $EDITOR opens in terminal
export VISUAL="emacsclient -c -a emacs"         # $VISUAL opens in GUI mode
#+end_example


** which key
Which key is a minor mode that displays the keybinding following your currently
entered incomplete command in a popup
#+begin_src emacs-lisp
(use-package which-key
    :init
    (setq which-key-side-window-location 'bottom
          which-key-sort-order #'which-key-key-order-alpha
          which-key-sort-uppercase-first nil
          which-key-add-column-padding 1
          which-key-max-display-columns nil
          which-key-min-display-lines 6
          which-key-side-window-slot -10
          which-key-side-window-max-height 0.25
          which-key-idle-delay 0.8
          which-key-max-description-length 25
          which-key-allow-imprecise-window-fit t
          which-key-separator " → " ))
(which-key-mode)
#+end_src

* Install packages
** setup melpa to enable install package
#+begin_src emacs-lisp

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)

(unless package-archive-contents
  (package-refresh-contents))

(package-initialize)

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)
#+end_src

** Setup straight
Straight is a packages manager that enables you to directly install Emacs packages
from git repositories

#+begin_src emacs-lisp

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

#+end_src


** install some package
*** general
General is a package that allows to setup your desired keybinding

#+begin_src emacs-lisp
(use-package general
    :config
    (general-evil-setup t))
#+end_src

*** Startup performance

#+begin_src emacs-lisp
(use-package gcmh
:config
(gcmh-mode 1))
;; Setting garbage collection threshold
(setq gc-cons-threshold 402653184
    gc-cons-percentage 0.6)

;; Profile emacs startup
(add-hook 'emacs-startup-hook
        (lambda ()
            (message "*** Emacs loaded in %s with %d garbage collections."
                    (format "%.2f seconds"
                            (float-time
                            (time-subtract after-init-time before-init-time)))
                    gcs-done)))

(setq gc-cons-threshold (* 50 1000 1000))

(defun efs/display-startup-time ()
(message "Emacs loaded in %s with %d garbage collections."
        (format "%.2f seconds"
                (float-time
                    (time-subtract after-init-time before-init-time)))
        gcs-done))

(add-hook 'emacs-startup-hook #'efs/display-startup-time)

#+end_src

*** ivy as completion mechanism

#+begin_src emacs-lisp
;; Ivy is a completion mechanism for Emacs. Ivy-rich allows you to add descriptions alongside the command M-x

(use-package counsel
    :after ivy
    :config (counsel-mode))
(use-package ivy
    :defer 0.1
    :diminish
    :bind
    (("C-c C-r" . ivy-resume)
    ("C-x B" . ivy-switch-buffer-other-window))
    :custom
    (setq ivy-count-format "(%d/%d) ")
    (setq ivy-use-virtual-buffers t)
    (setq enable-recursive-minibuffers t)
    :config
    (ivy-mode))
(use-package ivy-rich
    :after ivy
    :custom
    (ivy-virtual-abbreviate 'full
    ivy-rich-switch-buffer-align-virtual-buffer t
    ivy-rich-path-style 'abbrev)
    :config
    (ivy-set-display-transformer 'ivy-switch-buffer
                                'ivy-rich-switch-buffer-transformer)
    (ivy-rich-mode 1)) ;; this gets us descriptions in M-x.
(use-package swiper
    :after ivy
    :bind (("C-s" . swiper)
            ("C-r" . swiper)))
(setq ivi-initial-inputs-alist nil)
#+end_src

*** Install Smex
Smex is a package that makes M-x remember out history
#+begin_src emacs-lisp
(use-package smex)
(smex-initialize)
#+end_src

*** Flycheck to highlight errors
#+begin_src emacs-lisp
(use-package flycheck)
(flycheck-mode)
#+end_src

*** Copilot (not official)
#+begin_src emacs-lisp
(use-package copilot
  :straight (:host github :repo "zerolfx/copilot.el"
                   :files ("dist" "copilot.el"))
  :ensure t)

(add-hook 'prog-mode-hook 'copilot-mode)

#+end_src

**** Use copilot with company-mode

#+begin_src emacs-lisp
(with-eval-after-load 'company
  ;; disable inline previews
  (delq 'company-preview-if-just-one-frontend company-frontends))
  
(define-key copilot-completion-map (kbd "<tab>") 'copilot-accept-completion)
(define-key copilot-completion-map (kbd "TAB") 'copilot-accept-completion)

#+end_src


* Ivy-posframe
Ivy-posframe is an ivy extension, which lets ivy use posframe to show its candidate menu.  Some of the settings below involve:
- ivy-posframe-display-functions-alist -- sets the display position for specific programs
- ivy-posframe-height-alist -- sets the height of the list displayed for specific programs

Available functions (positions) for 'ivy-posframe-display-functions-alist'
- ivy-posframe-display-at-frame-center
- ivy-posframe-display-at-window-center
- ivy-posframe-display-at-frame-bottom-left
- ivy-posframe-display-at-window-bottom-left
- ivy-posframe-display-at-frame-bottom-window-center
- ivy-posframe-display-at-point
- ivy-posframe-display-at-frame-top-center

=NOTE:= If the setting for 'ivy-posframe-display' is set to 'nil' (false), anything that is set to 'ivy-display-function-fallback' will just default to their normal position in Doom Emacs (usually a bottom split).  However, if this is set to 't' (true), then the fallback position will be centered in the window.

#+begin_src emacs-lisp
  (use-package ivy-posframe
    :init
    (setq ivy-posframe-display-functions-alist
      '((swiper                     . ivy-posframe-display-at-point)
        (complete-symbol            . ivy-posframe-display-at-point)
        (counsel-M-x                . ivy-display-function-fallback)
        (counsel-esh-history        . ivy-posframe-display-at-window-center)
        (counsel-describe-function  . ivy-display-function-fallback)
        (counsel-describe-variable  . ivy-display-function-fallback)
        (counsel-find-file          . ivy-display-function-fallback)
        (counsel-recentf            . ivy-display-function-fallback)
        (counsel-register           . ivy-posframe-display-at-frame-bottom-window-center)
        (dmenu                      . ivy-posframe-display-at-frame-top-center)
        (nil                        . ivy-posframe-display))
      ivy-posframe-height-alist
      '((swiper . 20)
        (dmenu . 20)
        (t . 10)))
    :config
    (ivy-posframe-mode 1)) ; 1 enables posframe-mode, 0 disables it.
#+end_src

*** Install projectle
#+begin_src emacs-lisp

(use-package projectile
:config
(projectile-mode +1))
#+end_src

*** Setup evil mode
evil mode setup the vim keybinding
#+begin_src emacs-lisp

(use-package evil
:init      ;; tweak evil's configuration before loading it
;;  (setq evil-want-integration t) ;; This is optional since it's already set to t by default.
(setq evil-want-keybinding nil)
(setq evil-vsplit-window-right t)
(setq evil-split-window-below t)
(evil-mode)
)
(use-package evil-collection
 :after evil
 :config
 (setq evil-collection-mode-list '(dashboard dired ibuffer))
 (evil-collection-init))
 (use-package evil-tutor)
 (evil-mode t)
#+end_src

*** Install magit
Magit is a client for emacs
#+begin_src emacs-lisp
(setq bare-git-dir (concat "--git-dir=" (expand-file-name "~/.dotfiles")))
(setq bare-work-tree (concat "--work-tree=" (expand-file-name "~")))
;; use maggit on git bare repos like dotfiles repos, don't forget to change `bare-git-dir' and `bare-work-tree' to your needs
(defun me/magit-status-bare ()
"set --git-dir and --work-tree in `magit-git-global-arguments' to `bare-git-dir' and `bare-work-tree' and calls `magit-status'"
(interactive)
(require 'magit-git)
(add-to-list 'magit-git-global-arguments bare-git-dir)
(add-to-list 'magit-git-global-arguments bare-work-tree)
(call-interactively 'magit-status))

;; if you use `me/magit-status-bare' you cant use `magit-status' on other other repos you have to unset `--git-dir' and `--work-tree'
;; use `me/magit-status' insted it unsets those before calling `magit-status'
(defun me/magit-status ()
"removes --git-dir and --work-tree in `magit-git-global-arguments' and calls `magit-status'"
(interactive)
(require 'magit-git)
(setq magit-git-global-arguments (remove bare-git-dir magit-git-global-arguments))
(setq magit-git-global-arguments (remove bare-work-tree magit-git-global-arguments))
(call-interactively 'magit-status))

(use-package magit)

#+end_src

*** Files utilities

#+begin_src emacs-lisp
;;(use-package recentf
;;    :config
;;    (recentf-mode))
(use-package sudo-edit) ;; Utilities for opening files with sudo
#+end_src

*** Auto-complete
autocomplete engineering

#+begin_src emacs-lisp
(use-package company)
(company-mode)
#+end_src

*** cdlatex
cdlatex is a package that allows to display inline math expressions in latex
with the cdlatex mode
#+begin_src emacs-lisp
(use-package cdlatex)
(add-hook 'org-mode-hook #'turn-on-org-cdlatex)
#+end_src
*** some languages modes
#+begin_src emacs-lisp
(use-package markdown-mode)
(use-package web-mode)
#+end_src
**** plantuml need more configuration
#+begin_src emacs-lisp
(use-package plantuml-mode)
;; Sample jar configuration
(setq plantuml-jar-path "/opt/plantuml-1.2023.4.jar")
(setq plantuml-default-exec-mode 'jar)
#+end_src
**** Language server protocol
Language server protocol is an open protocol for use between source code editors
and servers that provide programming languages for some features

#+begin_src emacs-lisp
(use-package lsp-mode)
(use-package lsp-ui)

#+end_src

*** NEOTREE
Neotree is a file tree viewer.  When you open neotree, it jumps to the current
file thanks to neo-smart-open.  The neo-window-fixed-size setting makes the
neotree width be adjustable.  NeoTree provides following themes: classic, ascii,
arrow, icons, and nerd.  Theme can be configed by setting "two" themes for
neo-theme: one for the GUI and one for the terminal.  I like to use 'SPC t' for
'toggle' keybindings, so I have used 'SPC t n' for toggle-neotree.

| COMMAND        | DESCRIPTION               | KEYBINDING |
|----------------+---------------------------+------------|
| neotree-toggle | /Toggle neotree/            | SPC t n    |
| neotree- dir   | /Open directory in neotree/ | SPC d n    |

#+BEGIN_SRC emacs-lisp
;; Function for setting a fixed width for neotree.
;; Defaults to 25 but I make it a bit longer (35) in the 'use-package neotree'.
(defcustom neo-window-width 25
  "*Specifies the width of the NeoTree window."
  :type 'integer
  :group 'neotree)

(use-package neotree
  :config
  (setq neo-smart-open t
        neo-window-width 30
        neo-theme (if (display-graphic-p) 'icons 'arrow)
        ;;neo-window-fixed-size nil
        inhibit-compacting-font-caches t
        projectile-switch-project-action 'neotree-projectile-action) 
        ;; truncate long file names in neotree
        (add-hook 'neo-after-create-hook
           #'(lambda (_)
               (with-current-buffer (get-buffer neo-buffer-name)
                 (setq truncate-lines t)
                 (setq word-wrap nil)
                 (make-local-variable 'auto-hscroll-mode)
                 (setq auto-hscroll-mode nil)))))

;; show hidden files
(setq-default neo-show-hidden-files t)

(nvmap :prefix "SPC"
       "t n"   '(neotree-toggle :which-key "Toggle neotree file viewer")
       "d n"   '(neotree-dir :which-key "Open directory in neotree"))
#+END_SRC

* REGISTERS
Emacs registers are compartments where you can save text, rectangles and positions for later use. Once you save text or a rectangle in a register, you can copy it into the buffer once or many times; once you save a position in a register, you can jump back to that position once or many times.  The default GNU Emacs keybindings for these commands (with the exception of counsel-register) involves 'C-x r' followed by one or more other keys.  I wanted to make this a little more user friendly, so I chose to replace the 'C-x r' part of the key chords with 'SPC r'.

| COMMAND                          | DESCRIPTION                      | KEYBINDING |
|----------------------------------+----------------------------------+------------|
| copy-to-register                 | /Copy to register/                 | SPC r c    |
| frameset-to-register             | /Frameset to register/             | SPC r f    |
| insert-register                  | /Insert contents of register/      | SPC r i    |
| jump-to-register                 | /Jump to register/                 | SPC r j    |
| list-registers                   | /List registers/                   | SPC r l    |
| number-to-register               | /Number to register/               | SPC r n    |
| counsel-register                 | /Interactively choose a register/  | SPC r r    |
| view-register                    | /View a register/                  | SPC r v    |
| window-configuration-to-register | /Window configuration to register/ | SPC r w    |
| increment-register               | /Increment register/               | SPC r +    |
| point-to-register                | /Point to register/                | SPC r SPC  |

#+begin_src emacs-lisp
(nvmap :prefix "SPC"
       "r c"   '(copy-to-register :which-key "Copy to register")
       "r f"   '(frameset-to-register :which-key "Frameset to register")
       "r i"   '(insert-register :which-key "Insert register")
       "r j"   '(jump-to-register :which-key "Jump to register")
       "r l"   '(list-registers :which-key "List registers")
       "r n"   '(number-to-register :which-key "Number to register")
       "r r"   '(counsel-register :which-key "Choose a register")
       "r v"   '(view-register :which-key "View a register")
       "r w"   '(window-configuration-to-register :which-key "Window configuration to register")
       "r +"   '(increment-register :which-key "Increment register")
       "r SPC" '(point-to-register :which-key "Point to register"))
#+end_src

* File manager
Dired is the file manager whitin emacs. Below there is some custom keybinding
** Open dired
| Command    | Description                     | KEYBINDING |
| dired      | open dired                      | SPC d d    |
| dired-jump | open dired at current directory | SPC d j    |
** Keybinding within dired
| Command            | Description           | KEYBINDING |
| dired-view-file    | view files in dired   | SPC d v    |
| dired-up-directory | go up one dir         | h          |
| dired-find-file    | go down one directory | l          |

** Keybinding for peep-dired-mode
| Command              | Description    | KEYBINDING |
| peep-dired           | Toggle preview | SPC d p   |
| peep-dired-next-file | Next file      | n          |
| peep-dired-prev-file | Previous file  | p          |

#+begin_src emacs-lisp
(use-package all-the-icons-dired)
(use-package dired-open)
(use-package peep-dired)
(nvmap :states '(normal visual) :keymaps 'override :prefix "SPC"
                "d d" '(dired :which-key "Open dired")
                "d j" '(dired-jump :which-key "Dired jump to current")
                "d p" '(peep-dired :which-key "Peep-dired"))

(with-eval-after-load 'dired
(define-key dired-mode-map (kbd "M-p") 'peep-dired)
(evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
(evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
(evil-define-key 'normal peep-dired-mode-map (kbd "n") 'peep-dired-next-file)
(evil-define-key 'normal peep-dired-mode-map (kbd "p") 'peep-dired-prev-file))

(add-hook 'peep-dired-hook 'evil-normalize-keymaps)
;; Get file icons in dired
(add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
;; With dired-open plugin, you can launch external programs for certain extensions
;; For example, I set all .png files to open in 'sxiv' and all .mp4 files to open in 'mpv'
(setq dired-open-extensions '(("gif" . "sxiv")
                            ("jpg" . "sxiv")
                            ("png" . "sxiv")
                            ("mkv" . "mpv")
                            ("mp4" . "mpv")
                            ("pdf" . "evince")))
#+end_src


* keep folders clean
#+begin_src emacs-lisp
(use-package no-littering)

;; no-littering doesn't set this by default so we must place
;; auto save files in the same path as it uses for sessions
(setq auto-save-file-name-transforms
    `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))   

#+end_src
* Files
** Keybindings for files
| Command                   | Description    | KEYBINDINGS |
| find-file                 |                | SPC f f     |
| counsel-recentf           |                | SPC f r     |
| save-buffer               |                | SPC f s     |
| sudo-edit-find-file       |                | SPC f u     |
| show-and-copy-buffer-path |                | SPC f y     |
| copy-file                 |                | SPC f c     |
| delete-file               |                | SPC f d     |
| rename-file               |                | SPC f R     |
| write-file                | Save file as   | SPC f S     |
| sudo-edit                 | sudo edit file | SPC f U     |

#+begin_src emacs-lisp
(nvmap :states '(normal visual) :keymaps 'override :prefix "SPC"
        "."     '(find-file :which-key "Find file")
        "f f"   '(find-file :which-key "Find file")
        "f r"   '(counsel-recentf :which-key "Recent files")
        "f s"   '(save-buffer :which-key "Save file")
        "f u"   '(sudo-edit-find-file :which-key "Sudo find file")
        "f y"   '(dt/show-and-copy-buffer-path :which-key "Yank file path")
        "f c"   '(copy-file :which-key "Copy file")
        "f d"   '(delete-file :which-key "Delete file")
        "f R"   '(rename-file :which-key "Rename file")
        "f S"   '(write-file :which-key "Save file as...")
        "f U"   '(sudo-edit :which-key "Sudo edit file"))
#+end_src

** Useful file functions
#+begin_src emacs-lisp
(defun dt/show-and-copy-buffer-path ()
"Show and copy the full path to the current file in the minibuffer."
(interactive)
;; list-buffers-directory is the variable set in dired buffers
(let ((file-name (or (buffer-file-name) list-buffers-directory)))
    (if file-name
        (message (kill-new file-name))
    (error "Buffer not visiting a file"))))
(defun dt/show-buffer-path-name ()
"Show the full path to the current file in the minibuffer."
(interactive)
(let ((file-name (buffer-file-name)))
    (if file-name
        (progn
        (message file-name)
        (kill-new file-name))
    (error "Buffer not visiting a file"))))
#+end_src

* Customize UI
** display line numbers
In this seccion we enable display line in text mode and display de column line
#+begin_src emacs-lisp

;; display line numbers
(require 'display-line-numbers)


(defcustom display-line-numbers-exempt-modes
'(vterm-mode eshell-mode shell-mode term-mode ansi-term-mode)
"Major modes on which to disable line numbers."
:group 'display-line-numbers
:type 'list
:version "green")

(defun display-line-numbers--turn-on ()
"Turn on line numbers except for certain major modes.
Exempt major modes are defined in `display-line-numbers-exempt-modes'."
(unless (or (minibufferp)
            (member major-mode display-line-numbers-exempt-modes))
    (display-line-numbers-mode)))
(global-display-line-numbers-mode)
(setq column-number-mode t)
#+end_src

** clean ui
#+begin_src emacs-lisp
(setq inhibit-startup-message t)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(menu-bar-mode -1)
(setq visible-bell t)
(delete-selection-mode t)

#+end_src
** Install some themes and enable it

Also we enable doom-modeline and change the default font to fira code
#+begin_src emacs-lisp

;; set theme and font
;; (load-theme 'tsdh-dark)
(use-package dracula-theme)
;(load-theme 'dracula t)

(use-package doom-themes)
(setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
    doom-themes-enable-italic t) ; if nil, italics is universally disabled
(load-theme 'doom-one t)

(use-package doom-modeline)
(doom-modeline-mode 1)



(set-face-attribute 'default nil :font "Fira Code")
#+end_src

** Buffers and bookmarks
#+begin_src emacs-list
(nvmap :prefix "SPC"
       "b b"   '(ibuffer :which-key "Ibuffer")
       "b c"   '(clone-indirect-buffer-other-window :which-key "Clone indirect buffer other window")
       "b k"   '(kill-current-buffer :which-key "Kill current buffer")
       "b n"   '(next-buffer :which-key "Next buffer")
       "b p"   '(previous-buffer :which-key "Previous buffer")
       "b B"   '(ibuffer-list-buffers :which-key "Ibuffer list buffers")
       "b K"   '(kill-buffer :which-key "Kill buffer"))
#+end_src

* Customization

** Truncate lines in text mode
I dont want to get text with more than 80 charaters per line because readibility

#+begin_src emacs-lisp
(setq-default fill-column 80)
(add-hook 'text-mode-hook #'auto-fill-mode)

#+end_src

* DASHBOARD
Emacs Dashboard is an extensible startup screen showing you recent files, bookmarks, agenda items and an Emacs banner.

** Launch dashboard by default when launch emacs
#+begin_src emacs-lisp
(use-package all-the-icons)

  
(use-package dashboard
    :ensure t
    :init      ;; tweak dashboard config before loading it
    (setq dashboard-set-heading-icons t)
    (setq dashboard-set-file-icons t)
    (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
    ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
    (setq dashboard-startup-banner "~/.emacs.d/emacs-dash.png")  ;; use custom image as banner
    (setq dashboard-center-content nil) ;; set to 't' for centered content
    (setq dashboard-items '((recents . 5)
			    (agenda . 5 )
			    (bookmarks . 3)
			    (projects . 3)
			    (registers . 3)))
    :config
    (dashboard-setup-startup-hook)
    (dashboard-modify-heading-icons '((recents . "file-text")

				      (bookmarks . "book"))))
  ; ensure emacs open in dashboard
  (setq initial-buffer-choice (lambda () (get-buffer "*dashboard*")))
#+end_src

** Shortcuts
Allow to use escape to quit prompos
#+begin_src emacs-lisp
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+end_src


** Disable '^' of M-x
The following line removes the annoying ‘^’ in things like counsel-M-x and
other ivy/counsel prompts.  The default ‘^’ string means that if you type
something immediately after this string only completion candidates that begin
with what you typed are shown.  Most of the time, I’m searching for a command
without knowing what it begins with though.

#+begin_src emacs-lisp
(setq ivy-initial-inputs-alist nil)
#+end_src

** Disable mouse
#+begin_src emacs-lisp
(dolist (k '([mouse-1] [down-mouse-1] [drag-mouse-1] [double-mouse-1] [triple-mouse-1]  
             [mouse-2] [down-mouse-2] [drag-mouse-2] [double-mouse-2] [triple-mouse-2]
             [mouse-3] [down-mouse-3] [drag-mouse-3] [double-mouse-3] [triple-mouse-3]
             [mouse-4] [down-mouse-4] [drag-mouse-4] [double-mouse-4] [triple-mouse-4]
             [mouse-5] [down-mouse-5] [drag-mouse-5] [double-mouse-5] [triple-mouse-5]))
  (global-unset-key k))

#+end_src

* ORG MODE
This is the reason because i want to change to emacs leaving vim


** Org links
#+begin_src emacs-lisp
;; An example of how this works.
;; [[arch-wiki:Name_of_Page][Description]]
(setq org-link-abbrev-alist    ; This overwrites the default Doom org-link-abbrev-list
        '(("google" . "http://www.google.com/search?q=")
          ("arch-wiki" . "https://wiki.archlinux.org/index.php/")
          ("ddg" . "https://duckduckgo.com/?q=")
          ("wiki" . "https://en.wikipedia.org/wiki/")))
#+end_src

** Source code blocks

#+begin_src emacs-lisp
(setq org-src-fontify-natively t
    org-src-tab-acts-natively t
    org-confirm-babel-evaluate nil
    org-edit-src-content-indentation 0)
#+end_src
** Configure some vars

#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-indent-mode)
(setq org-directory "~/Documents/Org/"
      org-agenda-files '("~/Documents/Org/")
      org-default-notes-file (expand-file-name "notes.org" org-directory)
      org-default-todos-file (expand-file-name "todos.org" org-directory)
      org-ellipsis " ▼ "
      org-log-done 'time
      org-journal-dir "~/Documents/Or2/journal/"
      org-journal-date-format "%B %d, %Y (%A) "
      org-journal-file-format "%Y-%m-%d"
      org-default-journal-file (concat (expand-file-name (format-time-string org-journal-file-format) org-journal-dir) ".org")
      org-hide-emphasis-markers t)
(setq org-src-preserve-indentation nil
      org-src-tab-acts-natively t
      org-edit-src-content-indentation 0)

(use-package org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))

#+end_src

** Org capture
#+begin_src emacs-lisp
(setq org-capture-templates
      '(
            ("t" "Todo" entry (file+headline org-default-todos-file "Tasks.org")
                "* TODO %?\n  %i\n  %a")
            ("n" "Note" entry (file+headline org-default-notes-file "Notes.org")
                "* %?\n  %i\n  %a")
            ("j" "Journal" entry (file+datetree org-default-journal-file)
                "* %?\nEntered on %U\n  %i\n  %a")
         ))
#+end_src

Also we can define a template for org roam
#+begin_src emacs-lisp

(setq org-roam-capture-templates
      '(
        ("f" "Fleeting note" plain "%?"
        :target (file+head "01_FLEETING_NOTES/%<%Y%m%d%H%M%S>-${slug}.org"
            "#+title: ${title}\n")
            :unnarrowed t)
        ("l" "Literature note" plain "%?"
          :target (file+head "02_LITERATURE_NOTES/%<%Y%m%d%H%M%S>-${slug}.org"
          "#+title: ${title}\n") :unnarrowed t)
        ("p" "Permanent note" plain "%?"
          :target (file+head "03_PERMANENT_NOTES/%<%Y%m%d%H%M%S>-${slug}.org"
          "#+title: ${title}\n") :unnarrowed t)
        ("i" "Index note" plain "%?"
          :target (file+head "04_INDEX_NOTES/%<%Y%m%d%H%M%S>-${slug}.org"
          "#+title: ${title}\n") :unnarrowed t)
        )
      )

#+end_src
And insert some key binding
#+begin_src  emacs-lisp
(global-set-key (kbd "C-c l") #'org-store-link)
(global-set-key (kbd "C-c a") #'org-agenda)
(global-set-key (kbd "C-c c") #'org-capture)
(global-set-key (kbd "C-c r o") #'org-roam-node-find)
(global-set-key (kbd "C-c r i") #'org-id-get-create)

(use-package org-journal
    :ensure nil)
#+end_src

#+RESULTS:

** Org toc
#+begin_src emacs-lisp
(use-package toc-org
  :commands toc-org-enable
  :init (add-hook 'org-mode-hook 'toc-org-enable))
#+end_src

** Org export manpage
#+begin_src emacs-lisp
(use-package ox-man
  :ensure nil)
#+end_src

*** Org export to markdown
#+begin_src emacs-lisp
(use-package ox-gfm)
#+end_src
** Org-roam
#+begin_src emacs-lisp
(use-package org-roam)
(setq org-roam-directory (file-truename "~/Documents/Org2/"))
#+end_src
*** org-roam-ui
#+begin_src emacs-lisp
(use-package org-roam-ui)
#+end_src

** ORG-BABEL
#+begin_src emacs-lisp
(org-babel-do-load-languages
    'org-babel-load-languages
    '((python . t)
))
#+end_src
** Source Code Block Tag Expansion
Org-tempo is a package that allows for '<s' followed by TAB to expand to a begin_src tag.  Other expansions available include:

| Typing the below + TAB | Expands to ...                          |
|------------------------+-----------------------------------------|
| <a                     | '#+BEGIN_EXPORT ascii' … '#+END_EXPORT  |
| <c                     | '#+BEGIN_CENTER' … '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' … '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' … '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' … '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' … '#+END_EXPORT'  |
| <l                     | '#+BEGIN_EXPORT latex' … '#+END_EXPORT' |
| <q                     | '#+BEGIN_QUOTE' … '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' … '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' … '#+END_VERSE'         |

#+begin_src emacs-lisp
(use-package org-tempo
  :ensure nil) ;; tell use-package not to try to install org-tempo since it's already there.
#+end_src

** Skeletons
Skeleton is very powerful special-purpose mini-language implemented in
EmacsLisp. Typically, skeletons are used in conjunction with AbbrevMode for
automatic insertion of customized templates and such 

*** Journal template skeleton
#+begin_src emacs-lisp
(define-skeleton journla-skeleton
"This is a template to be launch in journal-mode"
"* DAY: " str | " insert day " " \n"
"_____"
"* Objetivos del día\n\n"
"* Cosas buenas de hoy\n\n"
"* Algo que haya aprendido\n\n"
"* Objetivos para mañana\n")
;; launch the skeleton with ^C-jr
#+end_src


* Custom hooks
A hook is a function that is launched when some event occur. In this section
will be some hooks that will be launch in some modes

#+begin_src emacs-lisp
(add-hook  'text-mode-hook (lambda () (flyspell-mode)))



#+end_src
