# -*- mode: shell-script -*- 
# custom alias
alias xclip='xclip -sel clipboard'
alias su='su -'
alias icat="kitty +kitten icat"
if [ -f /usr/bin/batcat ]; then
	alias cat=batcat
fi

# alias for old command replacemnet 
#if [ -f /usr/bin/nvim ]; then
	#alias vi=nvim
#fi

# Alias inteligentes para ls (eza > exa > lsd > ls)
if command -v eza >/dev/null 2>&1; then
    alias ls='eza --icons'
    alias ll='eza -lh --icons'
    alias la='eza -la --icons'
    alias lla='eza -lha --icons'
    alias lt='eza -T --icons'
    alias lg='eza -l --git --icons'
elif command -v exa >/dev/null 2>&1; then
    alias ls='exa'
    alias ll='exa -lh'
    alias la='exa -la'
    alias lla='exa -lha'
    alias lt='exa -T'
    alias lg='exa -l --git'
elif command -v lsd >/dev/null 2>&1; then
    alias ls='lsd'
    alias ll='lsd -lh'
    alias la='lsd -la'
    alias lla='lsd -lha'
    alias lt='lsd --tree'
else
    alias ll='ls -lh --color=auto'
    alias la='ls -la --color=auto'
    alias lla='ls -lah --color=auto'
    alias lt='ls -R --color=auto'
fi

if command -v batcat >/dev/null 2>&1; then
    alias cat='batcat --paging=never --style=plain'
elif command -v bat >/dev/null 2>&1; then
    alias cat='bat --paging=never --style=plain'
fi

if command -v rg >/dev/null 2>&1; then
    alias grep='rg'
fi

if command -v zoxide >/dev/null 2>&1; then
    eval "$(zoxide init bash)"
fi

if command -v tldr >/dev/null 2>&1; then
    alias man='tldr'
fi

# alias for git common commands
alias ggraph='git log --all --decorate --oneline --graph'
ginit() {
    mkdir "$1" && cd "$_" || exit
    echo "# $1" >> README.md
    git init
    git add README.md
    git commit -m "first commit"
    git branch -M main
    git remote add origin "git@github.com:luelvira/$1.git"
}
alias gsh='git push -u origin'
alias gl='git pull origin'
alias gss='git status'

# alias for custom functions
alias mkdir='mkdir -p'
tmptouch (){
	stamp=$(date +'%Y%m%d%H%M%s')
	touch "$1$stamp"
}
mkcd () {
	mkdir "$1" && cd "$_" || exit
}

tmpmkdir() {
	stamp=$(date +'%Y-%m-%d-%H.%M.%s')
	mkdir "$1$stamp"
}

gbackup() {
    stamp=$(date '+%Y-%m-%dT%H:%M')
    git commit -m $stamp
}
# make an alias to prevent accidental rm -rf
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

# SHOPT (https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html)
shopt -s autocd
shopt -s dotglob


if [ -f "/usr/bin/nvim" ]; then
    alias vim="nvim"
fi

alias emt="/usr/bin/emacs -nw"
alias emc="emacsclient -c -a 'emacs'"
alias rem="killall emacs || echo 'Emacs server not running'; /usr/bin/emacs --daemon"
