#! /bin/sh

DATEFTM="${DATEFTM:-+%a. %d. %b. %Y}"
SHORTFMT="${SHORTFMT:-+%d.%m.%Y}"
LABEL="${LABEL:-}"
blockdate=$(date "$DATEFTM")
shortblockdate=$(date "$SHORTFMT")

year=$(date '+%Y')
month=$(date '+%m')
case "$BLOCK_BUTTON" in
    1|2)
        date=$(date '+%a, %d. %B');;
    3)
        (( month == 12 )) && month=1 && year=$((year + 1)) || month=$((month + 1))
        date=$(cal $month $year | sed -n '1s/^  *//;1s/  *$//p')
esac
case "$BLOCK_BUTTON" in
    1|2|3)
export TERM=xterm
cal -3 $month $year \
    | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' \
    | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' \
    | rofi \
        -location 3 \
        -dmenu \
        -markup-rows \
        -no-fullscreen \
        -hide-scrollbar \
        -width -66 \
        -lines 8 \
        -no-custom \
        -font "DejaVu Sans Mono 9" \
        -theme glue_pro_blue \
        -p "$date" > /dev/null 
    esac
echo "$LABEL$blockdate"
echo "$LABEL$shortblockdate"
